### ISSUE TITLE
FO 4.0: Appartement I/ II

### ISSUE THREAD

**Issue by gerjantauw** [RuudvandenWijngaart/VestaDV#19]
In Concept Functioneel Ontwerp 4.0 is om de warmtevraag te berekenen gebruik gemaakt van verschillende woningtypes. Een onderscheid is gemaakt tussen appartement I en appartement II. Mijn vraag: Wat is het verschil tussen deze woningtypes?

**Comment by StevenvanPolen** [comment]
Het verschil tussen deze twee woningtypes zit in de hoogte van het gebouw.
Bij appartement I gaat het om flatgebouwen met 4 verdiepingen of minder en bij appartement II gaat het flatgebouwen met meer dan 4 verdiepingen.
