### ISSUE TITLE
Wanneer komen hier de gegevens voor de bijgewerkte (september 2020) versie ?

### ISSUE THREAD

**Issue by jan-perl** [RuudvandenWijngaart/VestaDV#21]
Wanneer komen hier de gegevens voor de bijgewerkte (september 2020) versie ?
https://www.expertisecentrumwarmte.nl/nieuws/1736151.aspx

**Comment by StevenvanPolen** [comment]
Ons streven is om deze maand nog een update te plaatsen van het model waarmee ook gerekend is voor de vernieuwde versie van de Startanalyse.

**Comment by jan-perl** [comment]
Met vesta50 is deze echt wel opgelost.
