### ISSUE TITLE
Kloppen de min/max bedragen voor warmtepompen in de file BCkentallen?

### ISSUE THREAD

**Issue by StefB93** [RuudvandenWijngaart/VestaDV#22]
In de file BCkentallen lijken de min/max bedragen voor bodemwarmtepompen omgekeerd (regel 52 en 53):

	parameter<Eur_kw>		Ki_w_BWP_var_min   :=	  899 [Eur_kw]      ,		Descr = "minimale variabele investering bodemwarmtepompen  door projectmatige collectieve aanpak";
	parameter<Eur_kw>		Ki_w_BWP_var_max   :=	  573 [Eur_kw]      ,		Descr = "maximale variabele investering bodemwarmtepompen  door niet-projectmatige aanpak";

**Comment by MolenvdF** [comment]
Dag Stef,

De lagere variabele kosten in de bovenwaarde worden gecompenseerd door de hogere vaste kosten. De stijlheid van de functie is daarmee anders maar wel hoger dan de onderwaarde. De functies zouden elkaar kruisen bij +/- 12 kW, maar dit is een waarde die in de praktijk bij woningen niet voorkomt binnen Vesta.

parameter<Eur_Aansl>	Ki_w_BWP_vast_min  :=	 4628 [Eur_Aansl]  ;
parameter<Eur_Aansl>	Ki_w_BWP_vast_max  :=	 8460 [Eur_Aansl]  ;
parameter<Eur_kw>	Ki_w_BWP_var_min   :=	  899 [Eur_kw] ;
parameter<Eur_kw>	Ki_w_BWP_var_max   :=	  573 [Eur_kw] ;

**Comment by StefB93** [comment]
Duidelijk!
