### ISSUE TITLE
Opstarten Vesta (na installatie) 'Delphi/gdal error'

### ISSUE THREAD

**Issue by ElsvdR** [RuudvandenWijngaart/VestaDV#26]
Ik heb alle installatieinstructies voor Vesta gevolgd. De mappenstructuur lijkt ook correct. Echter, als ik probeer het beschreven bestand bij het checken van de installatie te openen: /Invoer/RuimtelijkeData/WarmteBronnen/RestWarmte/BronSelecties/StartJaar/Bronnen/TypeInfoList_rel dan krijg ik als foutmelding "Delphi error:
Access violation at address 00007FFA2D83CD04 in module 'gdal111.dll'. Read of address 0000000000000058"

Vervolgens laad wel de tabel, maar niet de kaart waar de bronnen op zouden moeten staan.
![Uploading Vesta_error.png…]()

Heeft iemand enig idee wat hier aan de hand zou kunnen zijn en hoe ik dit op kan lossen? Alvast bedankt!

**Comment by eoudejans** [comment]
@ElsvdR, vermoedelijk heb je GeoDMS versie 8.044 geinstalleerd zoals beschreven in de documentatie. Inmiddels is GeoDMS van Delphi afgestapt en wordt een modernere versie van gdal (versie 3.8+) gebruikt. Zou je het nog eens kunnen proberen met een nieuwere [versie](https://github.com/ObjectVision/GeoDMS/releases/tag/v14.10.0) ?

Ik hoor graag of dat wel werkt.

**Comment by eoudejans** [comment]
Overigens goed om op te merken dat het vervolgmodel Hestia voortkomende uit Vesta inmiddels openbaar beschikbaar is op de Planbureau van de Leefomgeving Hestia Github omgeving: https://github.com/pbl-nl/model-hestia-public

**Comment by ElsvdR** [comment]
Dank voor je reactie! Op de wiki stond eerst nog een oudere versie van GeoDMS aangegeven (7.206). Ik sprak al met anderen binnen PBL (Wessel & Folckert) en dit moet dus 8.044 zijn, dat gaat beter. Naar aanleiding van mijn gesprek met Wessel is dit nu ook op de Wiki aangepast, dus ik denk dat het nu ook voor andere mensen die met Vesta aan de slag gaan is opgelost!
