### ISSUE TITLE
SourceData op ftp niet bereikbaar

### ISSUE THREAD

**Issue by SJJelles** [RuudvandenWijngaart/VestaDV#7]
Dag,
Ik probeer de SourceData zonder RO op te halen, maar het lijkt erop dat de ftp directory is verdwenen.
de map /anonymous staat wel in de directory van ftp://ftp.pbl.nl/ maar die kan ik niet openen.
Groet, prettig weekend, 
Sytse

PS: na al jullie rekenwerk voor de excellentie weer eens bijpraten?
Groet, Sytse

**Comment by RuudvandenWijngaart** [comment]
Dag Bas,
Kan jij reageren op het probleem dat Sytse Jelles aangeeft.
Dag Syste,
Bijpraten is oké. Op dit moment hebben we het nogal druk. Ik stel daarom voor om volgende maand contact op te nemen om een afspraak te maken. Als je al eerder concrete zaken wilt bespreken laat het dan weten.
Groeten, Ruud

**Comment by basvanbemmel** [comment]
Hallo Sytse,

Het ftp-beleid is bij ons laatst gewijzigd. 

Naar aanleiding van een melding van het NCSC (Nationaal Cyber Security Centrum) hebben we de anonieme toegang tot onze FTP server moeten beperken. De anonieme gebruiker mag alleen nog downloaden van een aantal vaste directories. Ik neem zo snel mogelijk contact op met de ftp-beheerder van het PBL om duidelijkheid te krijgen

Met vriendelijke groet,
Bas
